remote_theme: chrisrhymes/bulma-clean-theme
title: ModKit
permalink: pretty
favicon: /favicon.png
footer_menu: footer
paginate: 5
paginate_path: "/blog/page:num"

exclude: [ ".vscode", ".gitignore", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: post
      permalink: /blog/:year/:month/:day/:title/